<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf-576',
		'title' => '試合概要',
		'fields' => array (
			array (
				'key' => 'field_539e9a7c01c62',
				'label' => '試合日時',
				'name' => 'match_date',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e9a8e01c63',
				'label' => '対戦チーム',
				'name' => 'opponent',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e9a9b01c64',
				'label' => '節',
				'name' => 'section',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
//			array (
//				'key' => 'field_539e9b0c71080',
//				'label' => 'ステータス',
//				'name' => 'status',
//				'type' => 'text',
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'formatting' => 'html',
//				'maxlength' => '',
//			),
			array (
				'key' => 'field_539e9b3c71080',
				'label' => 'VIDEO',
				'name' => 'match_video',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e996a2c650',
				'label' => 'PIC',
				'name' => 'match_pic',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e9aa601c65',
				'label' => 'HOME合計点数',
				'name' => 'home_points',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e9ab101c66',
				'label' => '前後半スコア',
				'name' => 'half_all_score',
				'type' => 'textarea',
				'default_value' => 'v',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 3,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_539e9ac9093ae',
				'label' => 'AWAY合計点数',
				'name' => 'away_points',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'match',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 1,
	));

//	register_field_group(array (
//		'id' => 'acf-469',
//		'title' => '得点者',
//		'fields' => array (
//			array (
//				'key' => 'field_539e9aa601c6h',
//				'label' => 'HOME得点者',
//				'name' => 'hp_jugador',
//				'type' => 'textarea',
//				'default_value' => '',
//				'placeholder' => '',
//				'maxlength' => '',
//				'rows' => 3,
//				'formatting' => 'br',
//			),
//			array (
//				'key' => 'field_539e9ac9093aa',
//				'label' => 'AWAY得点者',
//				'name' => 'ap_jugador',
//				'type' => 'textarea',
//				'default_value' => '',
//				'placeholder' => '',
//				'maxlength' => '',
//				'rows' => 3,
//				'formatting' => 'br',
//			),
//		),
//		'location' => array (
//			array (
//				array (
//					'param' => 'post_type',
//					'operator' => '==',
//					'value' => 'match',
//					'order_no' => 0,
//					'group_no' => 0,
//				),
//			),
//		),
//		'options' => array (
//			'position' => 'normal',
//			'layout' => 'default',
//			'hide_on_screen' => array (
//			),
//		),
//		'menu_order' => 2,
//	));

	register_field_group(array (
		'id' => 'acf-464',
		'title' => '詳細',
		'fields' => array (
			array (
				'key' => 'field_5399703b3ab2f',
				'label' => 'ゴール(H) ',
				'name' => 'goal_home',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 3,
				'formatting' => 'br',
			),
//			array (
//				'key' => 'field_53996bcd075c2',
//				'label' => 'ゴール',
//				'name' => '',
//				'type' => 'message',
//				'message' => '<div id="goal_message">ゴール</div>',
//			),
			array (
				'key' => 'field_53996b856958e',
				'label' => 'ゴール(A)',
				'name' => 'goal_away',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 3,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_539974bfe7452',
				'label' => '警告(H) ',
				'name' => 'foul_home',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 4,
				'formatting' => 'br',
			),
//			array (
//				'key' => 'field_53997365dfaf7',
//				'label' => '警告',
//				'name' => '',
//				'type' => 'message',
//				'message' => '<div id="foul_message">警告</div>',
//			),
			array (
				'key' => 'field_53997538e7453',
				'label' => '警告(A) ',
				'name' => 'foul_away',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 4,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_539e98095f4a5',
				'label' => '退場(H)',
				'name' => 'home_leave',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
//			array (
//				'key' => 'field_539eb5177b921',
//				'label' => '退場',
//				'name' => '',
//				'type' => 'message',
//				'message' => '<div id="leave_message">退場</div>',
//			),
			array (
				'key' => 'field_539e982c5f4a6',
				'label' => '退場(A)',
				'name' => 'away_leave',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_539e983f5f4a7',
				'label' => '交代(H)',
				'name' => 'home_change',
				'type' => 'textarea',
				'default_value' => '→
→
→',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 6,
				'formatting' => 'br',
			),
//			array (
//				'key' => 'field_539eb5457b922',
//				'label' => '交代',
//				'name' => '',
//				'type' => 'message',
//				'message' => '<div id="change_message">交代</div>',
//			),
			array (
				'key' => 'field_539e98535f4a8',
				'label' => '交代(A)',
				'name' => 'away_change',
				'type' => 'textarea',
				'default_value' => '←
←
←',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 6,
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'match',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'featured_image',
				10 => 'tags',
				11 => 'send-trackbacks',
			),
		),
		'menu_order' => 3,
	));
	register_field_group(array (
		'id' => 'acf-575',
		'title' => 'メンバー',
		'fields' => array (
			array (
				'key' => 'field_539e99262c64d',
				'label' => 'チーム(H)',
				'name' => 'home_team',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
//			array (
//				'key' => 'field_539eb5e2f516f',
//				'label' => 'チーム',
//				'name' => '',
//				'type' => 'message',
//				'message' => '<div id="team_message">チーム</div>',
//			),
			array (
				'key' => 'field_539eac3b0590b',
				'label' => 'チーム(A)',
				'name' => 'away_team',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_539e99262c64c',
				'label' => 'スタメン(H)',
				'name' => 'home_teamst',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 14,
				'formatting' => 'br',
			),
//			array (
//				'key' => 'field_539eb5e2f516g',
//				'label' => 'スタメン',
//				'name' => '',
//				'type' => 'message',
//				'message' => '<div id="team_message">スタメン</div>',
//			),
			array (
				'key' => 'field_539eac3b0590a',
				'label' => 'スタメン(A)',
				'name' => 'away_teamst',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 14,
				'formatting' => 'br',
			),
//			array (
//				'key' => 'field_539e996a2c650',
//				'label' => 'GK(H)',
//				'name' => 'home_goal_keeper',
//				'type' => 'textarea',
//				'default_value' => '',
//				'placeholder' => '',
//				'maxlength' => '',
//				'rows' => 1,
//				'formatting' => 'br',
//			),
//			array (
//				'key' => 'field_539eb704fce7c',
//				'label' => 'GK',
//				'name' => '',
//				'type' => 'message',
//				'message' => '<div id="gk_message">GK</div>',
//			),
//			array (
//				'key' => 'field_539e99902c651',
//				'label' => 'GK(A)',
//				'name' => 'away_goal_keeper',
//				'type' => 'textarea',
//				'default_value' => '',
//				'placeholder' => '',
//				'maxlength' => '',
//				'rows' => 1,
//				'formatting' => 'br',
//			),
//			array (
//				'key' => 'field_539e999e2c652',
//				'label' => 'DF(H)',
//				'name' => 'home_defense',
//				'type' => 'textarea',
//				'default_value' => '',
//				'placeholder' => '',
//				'maxlength' => '',
//				'rows' => 4,
//				'formatting' => 'br',
//			),
//			array (
//				'key' => 'field_539eb647fce78',
//				'label' => 'DF',
//				'name' => '',
//				'type' => 'message',
//				'message' => '<div id="df_message">DF</div>',
//			),
//			array (
//				'key' => 'field_539e99bf2c653',
//				'label' => 'DF(A)',
//				'name' => 'away_defense',
//				'type' => 'textarea',
//				'default_value' => '',
//				'placeholder' => '',
//				'maxlength' => '',
//				'rows' => 4,
//				'formatting' => 'br',
//			),
//			array (
//				'key' => 'field_539e99cf2c654',
//				'label' => 'MF(H)',
//				'name' => 'home_midfielder',
//				'type' => 'textarea',
//				'default_value' => '',
//				'placeholder' => '',
//				'maxlength' => '',
//				'rows' => 5,
//				'formatting' => 'br',
//			),
//			array (
//				'key' => 'field_539eb667fce79',
//				'label' => 'MF',
//				'name' => '',
//				'type' => 'message',
//				'message' => '<div id="mf_message">MF</div>',
//			),
//			array (
//				'key' => 'field_539e99e12c655',
//				'label' => 'MF(A)',
//				'name' => 'away_midfielder',
//				'type' => 'textarea',
//				'default_value' => '',
//				'placeholder' => '',
//				'maxlength' => '',
//				'rows' => 5,
//				'formatting' => 'br',
//			),
//			array (
//				'key' => 'field_539e99f72c656',
//				'label' => 'FW(H)',
//				'name' => 'home_forward',
//				'type' => 'textarea',
//				'default_value' => '',
//				'placeholder' => '',
//				'maxlength' => '',
//				'rows' => 3,
//				'formatting' => 'br',
//			),
//			array (
//				'key' => 'field_539eb678fce7a',
//				'label' => 'FW',
//				'name' => '',
//				'type' => 'message',
//				'message' => '<div id="fw_message">FW</div>',
//			),
//			array (
//				'key' => 'field_539e9a0a2c657',
//				'label' => 'FW(A)',
//				'name' => 'away_forward',
//				'type' => 'textarea',
//				'default_value' => '',
//				'placeholder' => '',
//				'maxlength' => '',
//				'rows' => 3,
//				'formatting' => 'br',
//			),
			array (
				'key' => 'field_539e9a1b2c658',
				'label' => 'SU(H)',
				'name' => 'home_sub',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 7,
				'formatting' => 'br',
			),
//			array (
//				'key' => 'field_539eb684fce7b',
//				'label' => 'SU',
//				'name' => '',
//				'type' => 'message',
//				'message' => '<div id="su_message">SU</div>',
//			),
			array (
				'key' => 'field_539e9a302c659',
				'label' => 'SU(A)',
				'name' => 'away_sub',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 7,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_539e99382c64e',
				'label' => 'CO(H)',
				'name' => 'home_commanding_officer',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
//			array (
//				'key' => 'field_539eb613f5170',
//				'label' => 'CO',
//				'name' => '',
//				'type' => 'message',
//				'message' => '<div id="co_message">CO</div>',
//			),
			array (
				'key' => 'field_539e99582c64f',
				'label' => 'CO(A)',
				'name' => 'away_commanding_officer',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 1,
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'match',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 4,
	));
	register_field_group(array (
		'id' => 'acf_comp',
		'title' => 'コンペティション',
		'fields' => array (
			array (
				'key' => 'field_5b349466acb22',
				'label' => 'コンペティション',
				'name' => 'competition',
				'type' => 'select',
				'choices' => array (
					'icon_default' => 'None',
					'icon_laliga' => 'La Liga',
					'icon_ucl' => 'UCL',
					'icon_cdr' => 'COPA',
					'icon_icc' => 'ICC',
					'icon_usc' => 'USC',
					'icon_sce' => 'SCE',
					'icon_tb' => 'TSB',
					'icon_fcwc' => 'FCWC',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'match',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 5,
	));
}
